In [1]:
import torch
import numpy as np

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [16]:
d = torch.linspace(0,1,5).view(-1, 1)
i = torch.ones(4).view(-1, 1) * 2
b = torch.zeros(4).view(-1, 1)

d_len = d.shape[0]
i_len = i.shape[0]
b_len = b.shape[0]

print(d_len, i_len, b_len)

vec = torch.vstack((d, i, b))
print(vec[:d_len])
print(vec[d_len:d_len+i_len])
print(vec[d_len+i_len:d_len+i_len+b_len])


5 4 4
tensor([[0.0000],
        [0.2500],
        [0.5000],
        [0.7500],
        [1.0000]])
tensor([[2.],
        [2.],
        [2.],
        [2.]])
tensor([[0.],
        [0.],
        [0.],
        [0.]])
