In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from torch.utils.data import Dataset, DataLoader

np.random.seed(1234)

In [2]:
print(torch.cuda.get_device_name(torch.cuda.current_device()))  # GPU name

# CUDA support
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

NVIDIA GeForce RTX 2060
Using device: cuda


In [3]:
p = 20
bc_type = 3

x = torch.linspace(0, 1, p).view(-1, 1)
fixed = torch.ones(p) * 0
free = torch.ones(p) * 1
pinned = torch.ones(p) * 2

v_fixed = nn.functional.one_hot(fixed.to(torch.int64), num_classes=bc_type).to(torch.float32)
v_free = nn.functional.one_hot(free.to(torch.int64), num_classes=bc_type).to(torch.float32)
v_pinned = nn.functional.one_hot(pinned.to(torch.int64), num_classes=bc_type).to(torch.float32)




b1 = torch.cat((x, v_fixed, v_free), dim=1)
b2 = torch.cat((x, v_pinned, v_fixed), dim=1)
b3 = torch.cat((x, v_free, v_pinned), dim=1)
b4 = torch.cat((x, v_fixed, v_pinned), dim=1)
b5 = torch.cat((x, v_pinned, v_free), dim=1)
b6 = torch.cat((x, v_free, v_fixed), dim=1)

In [ ]:

class BeamDataset(Dataset):
    def __init__(self, num_samples_per_beam=100, beam_configs=None):
        """
        Args:
            num_samples_per_beam (int): Number of training points per beam configuration.
            beam_configs (list of dicts): Each dictionary contains the parameters of a beam problem.
        """
        self.data = []
        for config in beam_configs:
            x = torch.linspace(0, 1, num_samples_per_beam).view(-1, 1)  # Sampled x positions (normalized)
            p_bc = torch.tensor(config['p_bc'], dtype=torch.float32).repeat(num_samples_per_beam, 1)  # One-hot BCs
            w_true = torch.tensor(config['w'], dtype=torch.float32).view(-1, 1)  # Ground truth displacement

            self.data.append(torch.cat((x, p_bc, w_true), dim=1))  # Stack into a single tensor

        self.data = torch.cat(self.data, dim=0)  # Merge all beam configurations into one dataset

    def __len__(self):
        return self.data.shape[0]

    def __getitem__(self, idx):
        sample = self.data[idx]
        x = sample[0].unsqueeze(0)  # x position
        p_bc = sample[1:-1]  # Boundary condition encoding
        w_true = sample[-1]  # True displacement (optional, if supervised)
        return x, p_bc, w_true


In [5]:
class BeamData(Dataset):
    def __init__(self, num_points, beam_configs=None):
        

        self.data = []

        for config in beam_configs:
            x = config['x']
            lbc = torch.tensor(config['lbc'], dtype=torch.float).repeat(num_points, 1)
            rbc = torch.tensor(config['rbc'], dtype=torch.float).repeat(num_points, 1)

            self.data.append(torch.cat((x, lbc, rbc), dim=1))

        self.data = torch.cat(self.data, dim=0).requires_grad_()

    def __len__(self):
        return self.data.shape[0]
    
    def __getitem__(self, index):
        sample = self.data[index]
        return sample

In [6]:
class DNN(nn.Module):
    def __init__(self, layers):
        super(DNN, self).__init__()
        modules = []
        for i in range(len(layers) - 2):  # Exclude last layer for activation
            modules.append(nn.Linear(layers[i], layers[i+1]))
            modules.append(nn.Tanh())
        modules.append(nn.Linear(layers[-2], layers[-1]))  # Last layer (no activation)
        self.network = nn.Sequential(*modules)

        for layer in self.network:
            if isinstance(layer, nn.Linear):
                nn.init.xavier_uniform_(layer.weight)
                if layer.bias is not None:
                    nn.init.zeros_(layer.bias)

    def forward(self, x):
        return self.network(x)

In [20]:
p = 5
x = torch.linspace(0, 1, p).view(-1, 1)

fixed = [1, 0, 0]
pinned = [0, 1, 0]
free = [0, 0, 1]

layers = [7, 16, 2]

beam_configs = [
    {'x': x, 'lbc': fixed, 'rbc': free}, 
    {'x': x, 'lbc': pinned, 'rbc': fixed},
    {'x': x, 'lbc': free, 'rbc': pinned},
    {'x': x, 'lbc': fixed, 'rbc': pinned},
    {'x': x, 'lbc': pinned, 'rbc': free},
    {'x': x, 'lbc': free, 'rbc': fixed},
]

data = BeamData(p, beam_configs)
model = DNN(layers)

In [14]:
def model_output(sample):
    return model(sample)[:, 0:1]

In [ ]:
def boundary_condition(mask, data, u, u_x, m, m_x):
    loss = nn.MSELoss()

    bc_data = data[mask, 1:]
    bc_mask = bc_data.bool()
    u_bc, u_x_bc, m_bc, m_x_bc = u[mask], u_x[mask], m[mask], m_x[mask]
    
    bc_fixed = loss(u_bc[bc_mask[:, 0]], torch.ones_like(u_bc[bc_mask[:, 0]]))
    bc_fixed += loss(u_x_bc[bc_mask[:, 0]], torch.ones_like(u_x_bc[bc_mask[:, 0]]))

    bc_pinned = loss(u_bc[bc_mask[:, 1]], torch.ones_like(u_bc[bc_mask[:, 1]]))
    bc_pinned += loss(m_bc[bc_mask[:, 1]], torch.ones_like(m_bc[bc_mask[:, 1]]))

    bc_free = loss(m_bc[bc_mask[:, 2]], torch.ones_like(m_bc[bc_mask[:, 2]]))
    bc_free += loss(m_x_bc[bc_mask[:, 2]], torch.ones_like(m_x_bc[bc_mask[:, 2]]))

    total_loss = bc_fixed + bc_pinned + bc_free
    return total_loss




In [39]:
dataloader = DataLoader(data, batch_size=10, shuffle=True)
loss = nn.MSELoss()
for sample in dataloader:
    x = sample[:, 0:1]
    lbc = sample[:, 1:4]
    rbc = sample[:, 4:]

    out = model(sample)
    u = out[:, 0:1]

    mask_left = (sample[:, 0] == 0)
    mask_right = (sample[:, 0] == 1)
    
    bc_data = sample[mask_left, 1:]
    bc_mask = bc_data.bool()
    print(bc_data)
    print(bc_mask)
    u_bc = u[mask_left]
    print(u_bc)
    a = u_bc[bc_mask[:, 0]]
    print(a)

    break
    

tensor([[0., 1., 0., 0., 0., 1.],
        [0., 0., 1., 0., 1., 0.],
        [1., 0., 0., 0., 0., 1.]], grad_fn=<IndexBackward0>)
tensor([[False,  True, False, False, False,  True],
        [False, False,  True, False,  True, False],
        [ True, False, False, False, False,  True]])
tensor([[ 0.2451],
        [-0.3408],
        [-0.2196]], grad_fn=<IndexBackward0>)
tensor([[-0.2196]], grad_fn=<IndexBackward0>)


In [ ]:
class DNN(nn.Module):
    def __init__(self, layers):
        super(DNN, self).__init__()
        modules = []
        for i in range(len(layers) - 2):  # Exclude last layer for activation
            modules.append(nn.Linear(layers[i], layers[i+1]))
            modules.append(nn.Tanh())
        modules.append(nn.Linear(layers[-2], layers[-1]))  # Last layer (no activation)
        self.network = nn.Sequential(*modules)

        for layer in self.network:
            if isinstance(layer, nn.Linear):
                nn.init.xavier_uniform_(layer.weight)
                if layer.bias is not None:
                    nn.init.zeros_(layer.bias)

    def forward(self, x):
        return self.network(x)

In [ ]:
class PINN():
    def __init__(self, dataloader, layers):

        self.dataloader = dataloader
        self.dnn = DNN(layers).to(device)

        self.criterion = nn.MSELoss()
        self.optimizer_adam = torch.optim.Adam(self.dnn.parameters(), lr=0.01)

    def model_value(self, data):
        out = self.dnn(data)
        u = out[:, 0:1]
        m = out[:, 1:2]
        return u, m

    def boundary_condition(self, mask, data, u, u_x, m, m_x):
        loss = nn.MSELoss()

        bc_data = data[mask, 1:]
        bc_mask = bc_data.bool()
        u_bc, u_x_bc, m_bc, m_x_bc = u[mask], u_x[mask], m[mask], m_x[mask]
        
        bc_fixed = loss(u_bc[bc_mask[:, 0]], torch.ones_like(u_bc[bc_mask[:, 0]]))
        bc_fixed += loss(u_x_bc[bc_mask[:, 0]], torch.ones_like(u_x_bc[bc_mask[:, 0]]))

        bc_pinned = loss(u_bc[bc_mask[:, 1]], torch.ones_like(u_bc[bc_mask[:, 1]]))
        bc_pinned += loss(m_bc[bc_mask[:, 1]], torch.ones_like(m_bc[bc_mask[:, 1]]))

        bc_free = loss(m_bc[bc_mask[:, 2]], torch.ones_like(m_bc[bc_mask[:, 2]]))
        bc_free += loss(m_x_bc[bc_mask[:, 2]], torch.ones_like(m_x_bc[bc_mask[:, 2]]))

        total_loss = bc_fixed + bc_pinned + bc_free
        return total_loss

    def loss_func(self, data):
        u, m = self.model_value(data)

        mask_left = (data[:, 0] == 0)
        mask_right = (data[:, 1] == 1)

        ones = torch.ones_like(u)
        zeros = torch.zeros_like(u)

        u_x = torch.autograd.grad(u, data, ones, create_graph=True)[0][:, 0:1]
        u_2x = torch.autograd.grad(u_x, data, ones, create_graph=True)[0][:, 0:1]

        m_x = torch.autograd.grad(m, data, ones, create_graph=True)[0][:, 0:1]
        m_2x = torch.autograd.grad(m_x, data, ones, create_graph=True)[0][:, 0:1]

        bc_left_loss = self.boundary_condition(mask_left, data, u, u_x, m, m_x)
        bc_right_loss = self.boundary_condition(mask_right, data, u, u_x, m, m_x)

        pde_loss = self.criterion(m_2x - 1, zeros)
        pde_loss += self.criterion(u_2x + m, zeros)

        return pde_loss, bc_left_loss, bc_right_loss
        


    def train(self, epochs=1000):
        self.dnn.train()

        for epoch in range(epochs):
            for data_batch in self.dataset:
                pde_loss, bc_left_loss, bc_right_loss = self.loss_func(data_batch)
                loss = pde_loss + bc_left_loss + bc_right_loss
                
                self.optimizer_adam.zero_grad()
                loss.backward()
                self.optimizer_adam.step()

            if epoch % 100 == 0:
                print(f"Epoch {epoch}: Loss = {loss.item():.6f}")

In [ ]:


# Initialize model, loss, and optimizer
model = PINN(input_size=4)  # x (1D) + 3 BC encoding = 4 input features
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
num_epochs = 1000

for epoch in range(num_epochs):
    for x_batch, p_bc_batch, w_batch in dataloader:
        optimizer.zero_grad()
        w_pred = model(x_batch, p_bc_batch)
        loss = criterion(w_pred, w_batch)
        loss.backward()
        optimizer.step()
    
    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss = {loss.item():.6f}")


c:\Users\alexa\miniconda3\envs\pinn\Lib\site-packages\torch\nn\modules\loss.py:608: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
c:\Users\alexa\miniconda3\envs\pinn\Lib\site-packages\torch\nn\modules\loss.py:608: UserWarning: Using a target size (torch.Size([12])) that is different to the input size (torch.Size([12, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch 0: Loss = 0.420033
Epoch 100: Loss = 0.188474
Epoch 200: Loss = 0.380477
Epoch 300: Loss = 0.260603
Epoch 400: Loss = 0.534071
Epoch 500: Loss = 0.292803
Epoch 600: Loss = 0.239935
Epoch 700: Loss = 0.327213
Epoch 800: Loss = 0.178003
Epoch 900: Loss = 0.259345


In [ ]:
class DNN(nn.Module):
    def __init__(self, layers):
        super(DNN, self).__init__()
        modules = []
        for i in range(len(layers) - 2):  # Exclude last layer for activation
            modules.append(nn.Linear(layers[i], layers[i+1]))
            modules.append(nn.Tanh())
        modules.append(nn.Linear(layers[-2], layers[-1]))  # Last layer (no activation)
        self.network = nn.Sequential(*modules)

        for layer in self.network:
            if isinstance(layer, nn.Linear):
                nn.init.xavier_uniform_(layer.weight)
                if layer.bias is not None:
                    nn.init.zeros_(layer.bias)

    def forward(self, x):
        return self.network(x)

In [ ]:
class PINN():
    def __init__(self, layers, x, q, lb, rb):

        self.w_pde = 1.0
        self.w_bc = 1.0

        self.x = x
        self.q = q

        self.lb = lb
        self.rb = rb

        # DNN
        self.dnn = DNN(layers).to(device)

        # Optimizer
        self.optimizer_lbfgs = torch.optim.LBFGS(
            self.dnn.parameters(),
            lr=0.1,
            max_iter=50000,
            max_eval=50000,
            history_size=50,
            tolerance_grad=1e-7,
            tolerance_change=1.0 * np.finfo(float).eps,
            line_search_fn="strong_wolfe"
        )

        self.optimizer_adam = torch.optim.Adam(self.dnn.parameters(), lr=0.01)
        self.iter = 0

    def model_value(self, x):
        out = self.dnn(x)
        print(out)
        u = out[:,0].view(-1, 1)
        m = out[:,1].view(-1, 1)
        return u, m
    
    def boundary_cond(self, cond, u, u_x, m, m_x):
        bc_loss = 0

        match cond:
            case 'pinned':
                bc_loss += u**2 + m**2
            case 'fixed':
                bc_loss += u**2 + u_x**2
            case 'free':
                bc_loss += m**2 + m_x**2
            case 'roller':
                bc_loss += u_x**2 + m_x**2
        return bc_loss

    def loss_func(self, x):
        u, m = self.model_value(x)
        u_x = torch.autograd.grad(u, x, torch.ones_like(u), create_graph=True)[0]
        u_2x = torch.autograd.grad(u_x, x, torch.ones_like(u_x), create_graph=True)[0]

        m_x = torch.autograd.grad(m, x, torch.ones_like(m), create_graph=True)[0]
        m_2x = torch.autograd.grad(m_x, x, torch.ones_like(m_x), create_graph=True)[0]

        # BC
        bc_loss = self.boundary_cond(self.lb, u[0], u_x[0], m[0], m_x[0])
        bc_loss += self.boundary_cond(self.rb, u[-1], u_x[-1], m[-1], m_x[-1])

        # PDE
        pde_loss = torch.mean(torch.pow(m_2x + self.q, 2))
        pde_loss += torch.mean(torch.pow(u_2x + m, 2))

        return pde_loss, bc_loss


    def lbfgs_func(self):
        pde_loss, bc_loss = self.loss_func(self.x)
        loss = self.w_pde*pde_loss + self.w_bc*bc_loss

        self.optimizer_lbfgs.zero_grad()
        loss.backward()

        if self.iter % 100 == 0:
            print(f"Iter: {self.iter}, Loss: {'{:e}'.format(loss.item())}")
            print(f"PDE: {'{:e}'.format(pde_loss.item())}, BC: {'{:e}'.format(bc_loss.item())}")
        self.iter += 1
        return loss
    
    def train(self, epochs=1000):
        self.dnn.train()
        for epoch in range(epochs):
            pde_loss, bc_loss = self.loss_func(self.x)
            loss = self.w_pde*pde_loss + self.w_bc*bc_loss

            self.optimizer_adam.zero_grad()
            loss.backward()
            self.optimizer_adam.step()

            if epoch % 200 == 0:
                print(f"Epoch: {epoch}, Loss: {'{:e}'.format(loss.item())}")
                print(f"PDE: {'{:e}'.format(pde_loss.item())}, BC: {'{:e}'.format(bc_loss.item())}")
        # self.optimizer_lbfgs.step(self.lbfgs_func)

    def predict(self, X):
        x = torch.tensor(X, requires_grad=True).float().to(device)

        self.dnn.eval()
        u_c, m_c = self.model_value(x)
        u_c = u_c.detach().cpu().numpy()
        m_c = m_c.detach().cpu().numpy()
        return u_c, m_c